version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
       - echo "Codebuild has been started !"
  pre_build:
   commands:
       - cd scr 
       - docker build -t sample-function --platform linux/amd64 -t docker-image:test .
       - docker run --platform linux/amd64 -p 9000:8080 docker-image:test
       - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 113313628113.dkr.ecr.us-east-1.amazonaws.com