version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
       - echo "Codebuild has been started !"
  pre_build:
    commands:
       - cd scr 
       - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 113313628113.dkr.ecr.us-east-1.amazonaws.com
       - echo "Prebuilt command"
       - ls -l
    finally:
       - echo "Prebuilt finally"
       - ls -l

  build:
    commands:
       - docker build -t sample-function:latest --platform linux/amd64 .
       - docker tag sample-function:latest 113313628113.dkr.ecr.us-east-1.amazonaws.com/sample_function:latest
       - docker push 113313628113.dkr.ecr.us-east-1.amazonaws.com/sample_function:latest
       - aws lambda update-function-code sample-function --image-uri 113313628113.dkr.ecr.us-east-1.amazonaws.com/sample_function:latest
    finally:
       - echo "Build has been finished !"